# Generated by Django 5.1.2 on 2024-12-12 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.ImageField(default='null.jpg', upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=20)),
                ('description1', models.CharField(max_length=50)),
                ('price1', models.CharField(max_length=20)),
                ('image1', models.ImageField(default='null.jpg', upload_to='images')),
            ],
        ),
    ]
