# Generated by Django 5.1.2 on 2024-12-13 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='categories',
            field=models.CharField(default='default', max_length=50),
        ),
    ]
