# Generated by Django 5.1.2 on 2024-12-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0003_rename_categories_product_ctgy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ctgy',
        ),
    ]
