# Generated by Django 5.1.2 on 2024-12-14 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AdminApp', '0004_remove_product_ctgy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price1',
            field=models.IntegerField(),
        ),
    ]
