# Generated by Django 5.1.2 on 2025-01-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('UserApp', '0004_checkout'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkout',
            old_name='city',
            new_name='state',
        ),
        migrations.AlterField(
            model_name='checkout',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
